import { Translations } from './types';

export const translations: Translations = {
  en: {
    app_title: "ExaVMS",
    lpr_name: "License Plate Recognition",
    lpr_short_name: "Plates",
    traffic_name: "Vehicle Counting",
    traffic_short_name: "Counting",
    liveview_name: "Live View",
    liveview_short_name: "Live",
    configuration_name: "Configuration",
    configuration_short_name: "Configuration",
    events_name: "Recordings & Events",
    events_short_name: "Recordings",
    open_module: "Open Module",
    theme_switcher: "Toggle theme",
    language_selector: "Select language",
    go_back: "Go back",
    lpr_description: "This module handles real-time license plate recognition from video streams.",
    traffic_description: "This module provides analytics and counts for vehicular traffic.",
    liveview_description: "Professional VMS grid for live camera feeds with drag & drop and savable views.",
    configuration_description: "Add, edit, and manage global server configurations for all modules.",
    events_description: "Search, view, and download video recordings and AI-detected events.",

    // Login
    login_title: "Sign in to your account",
    login_username: "Username",
    login_password: "Password",
    login_button: "Login",
    login_error: "Invalid username or password.",
    login_remember_me: "Remember me",
    login_forgot_password: "Forgot Password?",

    // User Menu
    user_menu_logout: "Logout",
    user_role_admin: "Administrator",
    user_role_user: "User",
    user_role_viewer: "Viewer",

    // Live View
    liveview_sidebar_title: "Servers & Cameras",
    liveview_grid_layout: "Grid Layout",
    liveview_save_view: "Save View",
    liveview_view_name_placeholder: "Enter view name...",
    liveview_no_camera: "Drag a camera here",
    liveview_quality: "Quality",
    liveview_quality_main: "Main",
    liveview_quality_sub: "Sub",
    liveview_no_views: "No saved views",
    liveview_view_saved: "View saved successfully!",
    liveview_select_view: "Select a view to load",
    liveview_fullscreen: "Toggle Fullscreen",
    liveview_layout_tooltip_1x1: "1x1 Grid",
    liveview_layout_tooltip_2x2: "2x2 Grid",
    liveview_layout_tooltip_3x3: "3x3 Grid",
    'liveview_layout_tooltip_1+5': "1+5 Grid",
    'liveview_layout_tooltip_1+11': "1+11 Grid",
    liveview_saved_views_title: "Saved Views",
    liveview_personal_views: "My Views",
    liveview_shared_views: "Shared Views",
    liveview_rename_view: "Rename",
    liveview_delete_view: "Delete",
    liveview_delete_confirm_title: "Delete View",
    liveview_delete_confirm_text: "Are you sure you want to delete the view '{viewName}'? This action cannot be undone.",
    liveview_save_view_modal_title: "Save Current View",
    liveview_save_as_new: "Save as new view",
    liveview_overwrite_existing: "Overwrite existing view",
    liveview_enter_new_name: "Enter a name for the new view",
    liveview_select_view_to_overwrite: "Select a view to overwrite",
    liveview_save_button: "Save",
    liveview_cancel_button: "Cancel",
    liveview_no_personal_views: "You have no personal views to overwrite.",

    // Configuration Page
    config_tab_servers: "Servers",
    config_tab_lpr: "Plates",
    config_tab_traffic: "Counting",
    config_tab_users: "Users & Groups",
    config_tab_services: "Services",

    // Server Config
    server_config_add: "Add Server",
    server_config_table_name: "Name",
    server_config_table_url: "URL",
    server_config_table_status: "Status",
    server_config_table_resources: "Resources",
    server_config_table_actions: "Actions",
    server_config_modal_add_title: "Add New Server",
    server_config_modal_edit_title: "Edit Server",
    server_config_modal_name: "Server Name",
    server_config_modal_url: "Server URL",
    server_config_modal_token: "API Token (Optional)",
    server_config_modal_enabled: "Enabled",
    server_config_modal_save: "Save",
    server_config_modal_cancel: "Cancel",
    server_config_modal_delete: "Delete",
    server_config_modal_delete_confirm: "Are you sure you want to delete this server?",
    server_config_modal_token_help_title: "How to get an API Token?",
    server_config_modal_token_help_intro: "For services like Frigate that require authentication, you need to provide an API access token. Here's how to get one:",
    server_config_modal_token_help_step1_title: "Step 1: Authenticate via API",
    server_config_modal_token_help_step1_desc: "Use a tool like `curl` to send a POST request to the login endpoint of your service. Replace the placeholders with your actual server IP, username, and password.",
    server_config_modal_token_help_step2_title: "Step 2: Get the Token",
    server_config_modal_token_help_step2_desc: "The response will be a JSON object containing an `access_token`. Copy this token.",
    server_config_modal_token_help_step3_title: "Step 3: Paste the Token",
    server_config_modal_token_help_step3_desc: "Paste the copied token into the 'API Token' field above. The application will use this for all future requests to this server.",
    server_config_status_online: "Online",
    server_config_status_offline: "Offline",
    server_config_mqtt_title: "MQTT Configuration (Optional)",
    server_config_mqtt_host: "MQTT Host",
    server_config_mqtt_port: "MQTT Port",
    server_config_mqtt_user: "MQTT Username",
    server_config_mqtt_password: "MQTT Password",

    // Users & Groups
    users_manage_title: "User Management",
    users_add_user: "Add User",
    users_table_username: "Username",
    users_table_role: "Group",
    users_table_actions: "Actions",
    users_modal_add_title: "Add New User",
    users_modal_edit_title: "Edit User",
    users_modal_username: "Username",
    users_modal_password: "Password",
    users_modal_password_help: "Leave blank to keep current password",
    users_modal_role: "Group",
    users_delete_confirm: "Are you sure you want to delete the user '{username}'?",
    users_views_title: "View Sharing",
    users_views_description: "Share views created by administrators with user groups.",
    users_views_table_view: "View Name",
    users_views_table_owner: "Owner",
    users_views_share_user_group: "Share with 'User' group",
    users_views_share_viewer_group: "Share with 'Viewer' group",

    // Events Module
    events_search_filters: "Search Filters",
    events_search_by_time: "By Time",
    events_search_by_detection: "By Detections",
    events_server: "Server",
    events_all_servers: "All Servers",
    events_camera: "Camera",
    events_all_cameras: "All Cameras",
    events_date: "Date",
    events_time_range: "Time Range",
    events_object_types: "Object Types",
    events_search_button: "Search",
    events_searching: "Searching...",
    events_no_results: "No events found matching your criteria.",
    events_results_title: "Results",
    events_download_clip: "Download Clip",
    events_object_person: "Person",
    events_object_car: "Car",
    events_object_motorcycle: "Motorcycle",
    events_object_bicycle: "Bicycle",
    events_object_bus: "Bus",
    events_object_truck: "Truck",
    events_select_all: "Select All",
    events_clear_all: "Clear All",
  },
  es: {
    app_title: "ExaVMS",
    lpr_name: "Reconocimiento de Patentes",
    lpr_short_name: "Matrículas",
    traffic_name: "Conteo Vehicular",
    traffic_short_name: "Conteo",
    liveview_name: "Vista en Vivo",
    liveview_short_name: "Vivo",
    configuration_name: "Configuración",
    configuration_short_name: "Configuración",
    events_name: "Grabaciones y Eventos",
    events_short_name: "Grabaciones",
    open_module: "Abrir Módulo",
    theme_switcher: "Cambiar tema",
    language_selector: "Seleccionar idioma",
    go_back: "Volver",
    lpr_description: "Este módulo gestiona el reconocimiento de patentes en tiempo real desde flujos de video.",
    traffic_description: "Este módulo proporciona análisis y conteos del tráfico vehicular.",
    liveview_description: "Grilla VMS profesional para cámaras en vivo con arrastrar y soltar y vistas guardables.",
    configuration_description: "Añada, edite y gestione configuraciones globales de servidores para todos los módulos.",
    events_description: "Busque, visualice y descargue grabaciones de video y eventos detectados por IA.",
    
    // Login
    login_title: "Inicia sesión en tu cuenta",
    login_username: "Usuario",
    login_password: "Contraseña",
    login_button: "Iniciar Sesión",
    login_error: "Usuario o contraseña incorrectos.",
    login_remember_me: "Recordarme",
    login_forgot_password: "¿Olvidaste tu contraseña?",

    // User Menu
    user_menu_logout: "Cerrar Sesión",
    user_role_admin: "Administrador",
    user_role_user: "Usuario",
    user_role_viewer: "Visualizador",

    // Live View
    liveview_sidebar_title: "Servidores y Cámaras",
    liveview_grid_layout: "Disposición de Grilla",
    liveview_save_view: "Guardar Vista",
    liveview_view_name_placeholder: "Ingrese nombre de la vista...",
    liveview_no_camera: "Arrastre una cámara aquí",
    liveview_quality: "Calidad",
    liveview_quality_main: "Principal",
    liveview_quality_sub: "Secundaria",
    liveview_no_views: "No hay vistas guardadas",
    liveview_view_saved: "¡Vista guardada con éxito!",
    liveview_select_view: "Seleccione una vista para cargar",
    liveview_fullscreen: "Activar/Desactivar Pantalla Completa",
    liveview_layout_tooltip_1x1: "Grilla 1x1",
    liveview_layout_tooltip_2x2: "Grilla 2x2",
    liveview_layout_tooltip_3x3: "Grilla 3x3",
    'liveview_layout_tooltip_1+5': "Grilla 1+5",
    'liveview_layout_tooltip_1+11': "Grilla 1+11",
    liveview_saved_views_title: "Vistas Guardadas",
    liveview_personal_views: "Mis Vistas",
    liveview_shared_views: "Vistas Compartidas",
    liveview_rename_view: "Renombrar",
    liveview_delete_view: "Eliminar",
    liveview_delete_confirm_title: "Eliminar Vista",
    liveview_delete_confirm_text: "¿Está seguro de que desea eliminar la vista '{viewName}'? Esta acción no se puede deshacer.",
    liveview_save_view_modal_title: "Guardar Vista Actual",
    liveview_save_as_new: "Guardar como nueva vista",
    liveview_overwrite_existing: "Sobrescribir vista existente",
    liveview_enter_new_name: "Ingrese un nombre para la nueva vista",
    liveview_select_view_to_overwrite: "Seleccione una vista para sobrescribir",
    liveview_save_button: "Guardar",
    liveview_cancel_button: "Cancelar",
    liveview_no_personal_views: "No tiene vistas personales para sobrescribir.",

    // Configuration Page
    config_tab_servers: "Servidores",
    config_tab_lpr: "Matrículas",
    config_tab_traffic: "Conteo",
    config_tab_users: "Usuarios y Grupos",
    config_tab_services: "Servicios",

    // Server Config
    server_config_add: "Añadir Servidor",
    server_config_table_name: "Nombre",
    server_config_table_url: "URL",
    server_config_table_status: "Estado",
    server_config_table_resources: "Recursos",
    server_config_table_actions: "Acciones",
    server_config_modal_add_title: "Añadir Nuevo Servidor",
    server_config_modal_edit_title: "Editar Servidor",
    server_config_modal_name: "Nombre del Servidor",
    server_config_modal_url: "URL del Servidor",
    server_config_modal_token: "Token de API (Opcional)",
    server_config_modal_enabled: "Habilitado",
    server_config_modal_save: "Guardar",
    server_config_modal_cancel: "Cancelar",
    server_config_modal_delete: "Eliminar",
    server_config_modal_delete_confirm: "¿Está seguro de que desea eliminar este servidor?",
    server_config_modal_token_help_title: "¿Cómo obtener un Token de API?",
    server_config_modal_token_help_intro: "Para servicios como Frigate que requieren autenticación, necesita proporcionar un token de acceso a la API. A continuación se explica cómo obtener uno:",
    server_config_modal_token_help_step1_title: "Paso 1: Autenticarse a través de la API",
    server_config_modal_token_help_step1_desc: "Use una herramienta como `curl` para enviar una solicitud POST al endpoint de login de su servicio. Reemplace los valores de ejemplo con la IP de su servidor, su usuario y contraseña.",
    server_config_modal_token_help_step2_title: "Paso 2: Obtener el Token",
    server_config_modal_token_help_step2_desc: "La respuesta será un objeto JSON que contiene un `access_token`. Copie este token.",
    server_config_modal_token_help_step3_title: "Paso 3: Pegar el Token",
    server_config_modal_token_help_step3_desc: "Pegue el token copiado en el campo 'Token de API' de arriba. La aplicación lo usará para todas las futuras solicitudes a este servidor.",
    server_config_status_online: "En línea",
    server_config_status_offline: "Fuera de línea",
    server_config_mqtt_title: "Configuración MQTT (Opcional)",
    server_config_mqtt_host: "Host MQTT",
    server_config_mqtt_port: "Puerto MQTT",
    server_config_mqtt_user: "Usuario MQTT",
    server_config_mqtt_password: "Contraseña MQTT",

    // Users & Groups
    users_manage_title: "Gestión de Usuarios",
    users_add_user: "Añadir Usuario",
    users_table_username: "Usuario",
    users_table_role: "Grupo",
    users_table_actions: "Acciones",
    users_modal_add_title: "Añadir Nuevo Usuario",
    users_modal_edit_title: "Editar Usuario",
    users_modal_username: "Nombre de usuario",
    users_modal_password: "Contraseña",
    users_modal_password_help: "Dejar en blanco para mantener la contraseña actual",
    users_modal_role: "Grupo",
    users_delete_confirm: "¿Está seguro de que desea eliminar al usuario '{username}'?",
    users_views_title: "Compartir Vistas",
    users_views_description: "Comparta vistas creadas por administradores con otros grupos de usuarios.",
    users_views_table_view: "Nombre de la Vista",
    users_views_table_owner: "Propietario",
    users_views_share_user_group: "Compartir con grupo 'Usuario'",
    users_views_share_viewer_group: "Compartir con grupo 'Visualizador'",

    // Events Module
    events_search_filters: "Filtros de Búsqueda",
    events_search_by_time: "Por Hora",
    events_search_by_detection: "Por Detecciones",
    events_server: "Servidor",
    events_all_servers: "Todos los servidores",
    events_camera: "Cámara",
    events_all_cameras: "Todas las cámaras",
    events_date: "Fecha",
    events_time_range: "Rango Horario",
    events_object_types: "Tipos de Objeto",
    events_search_button: "Buscar",
    events_searching: "Buscando...",
    events_no_results: "No se encontraron eventos que coincidan con sus criterios.",
    events_results_title: "Resultados",
    events_download_clip: "Descargar Clip",
    events_object_person: "Persona",
    events_object_car: "Auto",
    events_object_motorcycle: "Moto",
    events_object_bicycle: "Bicicleta",
    events_object_bus: "Colectivo",
    events_object_truck: "Camión",
    events_select_all: "Seleccionar Todo",
    events_clear_all: "Limpiar Todo",
  },
  pt: {
    app_title: "ExaVMS",
    lpr_name: "Reconhecimento de Placas",
    lpr_short_name: "Placas",
    traffic_name: "Contagem de Veículos",
    traffic_short_name: "Contagem",
    liveview_name: "Visualização ao Vivo",
    liveview_short_name: "Ao Vivo",
    configuration_name: "Configuração",
    configuration_short_name: "Config",
    events_name: "Gravações e Eventos",
    events_short_name: "Gravações",
    open_module: "Abrir Módulo",
    theme_switcher: "Alternar tema",
    language_selector: "Selecionar idioma",
    go_back: "Voltar",
    lpr_description: "Este módulo gerencia o reconhecimento de placas em tempo real a partir de streams de vídeo.",
    traffic_description: "Este módulo fornece análises e contagens de tráfego de veículos.",
    liveview_description: "Grade VMS profissional para feeds de câmera ao vivo com arrastar e soltar e visualizações salváveis.",
    configuration_description: "Adicione, edite e gerencie configurações globais de servidor para todos os módulos.",
    events_description: "Pesquise, visualize e baixe gravações de vídeo e eventos detectados por IA.",

    // Login
    login_title: "Faça login na sua conta",
    login_username: "Usuário",
    login_password: "Senha",
    login_button: "Entrar",
    login_error: "Nome de usuário ou senha inválidos.",
    login_remember_me: "Lembrar-me",
    login_forgot_password: "Esqueceu a senha?",

    // User Menu
    user_menu_logout: "Sair",
    user_role_admin: "Administrador",
    user_role_user: "Usuário",
    user_role_viewer: "Visualizador",

    // Live View
    liveview_sidebar_title: "Servidores e Câmeras",
    liveview_grid_layout: "Layout da Grade",
    liveview_save_view: "Salvar Visualização",
    liveview_view_name_placeholder: "Digite o nome da visualização...",
    liveview_no_camera: "Arraste uma câmera aqui",
    liveview_quality: "Qualidade",
    liveview_quality_main: "Principal",
    liveview_quality_sub: "Sub",
    liveview_no_views: "Nenhuma visualização salva",
    liveview_view_saved: "Visualização salva com sucesso!",
    liveview_select_view: "Selecione uma visualização para carregar",
    liveview_fullscreen: "Alternar Tela Cheia",
    liveview_layout_tooltip_1x1: "Grade 1x1",
    liveview_layout_tooltip_2x2: "Grade 2x2",
    liveview_layout_tooltip_3x3: "Grade 3x3",
    'liveview_layout_tooltip_1+5': "Grade 1+5",
    'liveview_layout_tooltip_1+11': "Grade 1+11",
    liveview_saved_views_title: "Vistas Salvas",
    liveview_personal_views: "Minhas Vistas",
    liveview_shared_views: "Vistas Compartilhadas",
    liveview_rename_view: "Renomear",
    liveview_delete_view: "Excluir",
    liveview_delete_confirm_title: "Excluir Visualização",
    liveview_delete_confirm_text: "Tem certeza de que deseja excluir a visualização '{viewName}'? Esta ação não pode ser desfeita.",
    liveview_save_view_modal_title: "Salvar Visualização Atual",
    liveview_save_as_new: "Salvar como nova visualização",
    liveview_overwrite_existing: "Sobrescrever visualização existente",
    liveview_enter_new_name: "Digite um nome para a nova visualização",
    liveview_select_view_to_overwrite: "Selecione uma visualização para sobrescrever",
    liveview_save_button: "Salvar",
    liveview_cancel_button: "Cancelar",
    liveview_no_personal_views: "Você não tem visualizações pessoais para sobrescrever.",


    // Configuration Page
    config_tab_servers: "Servidores",
    config_tab_lpr: "Placas",
    config_tab_traffic: "Contagem",
    config_tab_users: "Usuários e Grupos",
    config_tab_services: "Serviços",

    // Server Config
    server_config_add: "Adicionar Servidor",
    server_config_table_name: "Nome",
    server_config_table_url: "URL",
    server_config_table_status: "Status",
    server_config_table_resources: "Recursos",
    server_config_table_actions: "Ações",
    server_config_modal_add_title: "Adicionar Novo Servidor",
    server_config_modal_edit_title: "Editar Servidor",
    server_config_modal_name: "Nome do Servidor",
    server_config_modal_url: "URL do Servidor",
    server_config_modal_token: "Token da API (Opcional)",
    server_config_modal_enabled: "Habilitado",
    server_config_modal_save: "Salvar",
    server_config_modal_cancel: "Cancelar",
    server_config_modal_delete: "Excluir",
    server_config_modal_delete_confirm: "Tem certeza de que deseja excluir este servidor?",
    server_config_modal_token_help_title: "Como obter um Token de API?",
    server_config_modal_token_help_intro: "Para serviços como o Frigate que exigem autenticação, você precisa fornecer um token de acesso à API. Veja como obter um:",
    server_config_modal_token_help_step1_title: "Passo 1: Autenticar via API",
    server_config_modal_token_help_step1_desc: "Use uma ferramenta como `curl` para enviar uma solicitação POST para o endpoint de login do seu serviço. Substitua os placeholders pelo IP do seu servidor, nome de usuário e senha reais.",
    server_config_modal_token_help_step2_title: "Passo 2: Obter o Token",
    server_config_modal_token_help_step2_desc: "A resposta será um objeto JSON contendo um `access_token`. Copie este token.",
    server_config_modal_token_help_step3_title: "Passo 3: Colar o Token",
    server_config_modal_token_help_step3_desc: "Cole o token copiado no campo 'Token da API' acima. O aplicativo usará isso para todas as futuras solicitações a este servidor.",
    server_config_status_online: "Online",
    server_config_status_offline: "Offline",
    server_config_mqtt_title: "Configuração MQTT (Opcional)",
    server_config_mqtt_host: "Host MQTT",
    server_config_mqtt_port: "Porta MQTT",
    server_config_mqtt_user: "Usuário MQTT",
    server_config_mqtt_password: "Senha MQTT",

    // Users & Groups
    users_manage_title: "Gerenciamento de Usuários",
    users_add_user: "Adicionar Usuário",
    users_table_username: "Nome de usuário",
    users_table_role: "Grupo",
    users_table_actions: "Ações",
    users_modal_add_title: "Adicionar Novo Usuário",
    users_modal_edit_title: "Editar Usuário",
    users_modal_username: "Nome de usuário",
    users_modal_password: "Senha",
    users_modal_password_help: "Deixe em branco para manter a senha atual",
    users_modal_role: "Grupo",
    users_delete_confirm: "Tem certeza de que deseja excluir o usuário '{username}'?",
    users_views_title: "Compartilhamento de Vistas",
    users_views_description: "Compartilhe vistas criadas por administradores com outros grupos de usuários.",
    users_views_table_view: "Nome da Vista",
    users_views_table_owner: "Proprietário",
    users_views_share_user_group: "Compartilhar com grupo 'Usuário'",
    users_views_share_viewer_group: "Compartilhar com grupo 'Visualizador'",
    
    // Events Module
    events_search_filters: "Filtros de Pesquisa",
    events_search_by_time: "Por Hora",
    events_search_by_detection: "Por Detecções",
    events_server: "Servidor",
    events_all_servers: "Todos os servidores",
    events_camera: "Câmera",
    events_all_cameras: "Todas as câmeras",
    events_date: "Data",
    events_time_range: "Intervalo de Tempo",
    events_object_types: "Tipos de Objeto",
    events_search_button: "Pesquisar",
    events_searching: "Pesquisando...",
    events_no_results: "Nenhum evento encontrado para os seus critérios.",
    events_results_title: "Resultados",
    events_download_clip: "Baixar Clipe",
    events_object_person: "Pessoa",
    events_object_car: "Carro",
    events_object_motorcycle: "Motocicleta",
    events_object_bicycle: "Bicicleta",
    events_object_bus: "Ônibus",
    events_object_truck: "Caminhão",
    events_select_all: "Selecionar Tudo",
    events_clear_all: "Limpar Tudo",
  },
};